#ci.gocd.yaml
format_version: 2

pipelines:
  yaml_build_test:
    group: KenTest
    materials:
      appGit:
        git: https://github.com/gocd-demo/jy_main_repo.git
        branch: master
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: "docker-maven"
              tasks:
                - exec:
                    command: mvn
                    arguments:
                     - clean
                - exec:
                    command: mvn
                    arguments:
                     - compile
                     - -DskipTests
      - test:
          jobs:
            unit_test:
              elastic_profile_id: "docker-maven"
              tasks:
                - exec:
                    command: mvn
                    arguments:
                     - clean
                     - test

